name: Generate Snake + Clock

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Sonic-12
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake.svg

      - run: sudo chown -R $USER:$USER dist

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: python .github/scripts/generate_clock.py

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}